### ISSUE TITLE
Support Dockerfile for Windows

### ISSUE THREAD

**Issue by ghost** [mathworks-ref-arch/container-images#1]
It's very cool to use matlab in docker, but i missing the posibility to run matlab in Windows based docker image.

Do Mathworks support this?

**Comment by prabhakk-mw** [comment]
Hi @MaSc265 

Thank you!
We do not have a Dockerfile which can be used with Windows base images.
Windows based docker containers are limited in terms of their capabilities, for example: they do not provide any desktop support. 

We are closely monitoring the updates to support to the windows base layer, and look to publish a Dockerfile which showcases its use as it matures.
This said, community members were able to install MATLAB onto Windows and use it for their internal CI/CD workflows.

Also, FYI. The [matlab-dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile) repository, lists a Dockerfile which showcases ways to easily install MATLAB into linux containers.
