### ISSUE TITLE
Missing files in Matlab

### ISSUE THREAD

**Issue by marmal88** [mathworks-ref-arch/container-images#6]
Hello, 

I realised that current build (R2023a) has moved the following files, 

1. would it be possible to have the locations of these new files?
    - /usr/local/bin/matlab-proxy-app
    - /usr/local/bin/matlab-proxy-app-list-servers

2. Are the files in the location `/usr/local/bin/matlab` all that's required to run matlab?

**Comment by prabhakk-mw** [comment]
Hi @marmal88 

I find the WHICH command to be very useful in these situations, and coupled along with the READLINK command can also provide where the executable really lives in case it has been softlinked.

In this case for `matlab-proxy-app`:

```bash

matlab@f5680d616a57:~/Documents/MATLAB$ which matlab-proxy-app
/home/matlab/.local/bin/matlab-proxy-app
matlab@f5680d616a57:~/Documents/MATLAB$ readlink -f `which matlab-proxy-app`
/home/matlab/.local/pipx/venvs/matlab-proxy/bin/matlab-proxy-app

```

Similarly one could run the commands for the `matlab` executable as well.

```bash
matlab@f5680d616a57:~/Documents/MATLAB$ which matlab
/usr/local/bin/matlab
matlab@f5680d616a57:~/Documents/MATLAB$ readlink -f `which matlab`
/opt/matlab/R2023a/bin/matlab
```

MATLAB is installed in `/opt/matlab/R2023a` and all the files required to use MATLAB are present under this location.

`/usr/local/bin/matlab` is a soft link to the matlab executable under this location.

Please do let us know if there is any more information that we could help with.

Thank you
